syzechuan:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: syzechuan_delivery
    username: root
    password: Zzt!12345

  alioss:
    access-key-id: LTAI5tSoMRUE7LjemCzFjXoE
    endpoint: oss-us-east-1.aliyuncs.com
    access-key-secret: YFz1Pke4TKaER8juqqcKpIURCKQ842
    bucket-name: syzechuan-itcast

  redis:
    host: localhost
    port: 6379
    password: Zzt!12345
    database: 10
