server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${syzechuan.datasource.driver-class-name}
      url: jdbc:mysql://${syzechuan.datasource.host}:${syzechuan.datasource.port}/${syzechuan.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${syzechuan.datasource.username}
      password: ${syzechuan.datasource.password}
  redis:
    host: ${syzechuan.redis.host}
    port: ${syzechuan.redis.port}
    password: ${syzechuan.redis.password}
    database: ${syzechuan.redis.database}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.syzechuan.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

syzechuan:
  jwt:
    admin-secret-key: itcast
    admin-ttl: 72000000
    admin-token-name: token
    user-secret-key: itheima
    user-ttl: 72000000
    user-token-name: authentication

  alioss:
    endpoint: ${syzechuan.alioss.endpoint}
    access-key-id: ${syzechuan.alioss.access-key-secret}
    access-key-secret: ${syzechuan.alioss.access-key-secret}
    bucket-name: ${syzechuan.alioss.bucket-name}

  wechat:
    appid: ${syzechuan.wechat.appid}
    secret: ${syzechuan.wechat.secret}
    mchid: ${syzechuan.wechat.mchid}
    mch-serial-no: ${syzechuan.wechat.mch-serial-no}
    private-key-file-path: ${syzechuan.wechat.private-key-file-path}
    api-v3-key: ${syzechuan.wechat.api-v3-key}
    we-chat-pay-cert-file-path: ${syzechuan.wechat.we-chat-pay-cert-file-path}
    notify-url: ${syzechuan.wechat.notify-url}
    refund-notify-url:  ${syzechuan.wechat.refund-notify-url}
